---
version: 1.0.0-{build}

image: Ubuntu1804-minimal

environment:
  CLOUDBOX_BRANCH: "develop_python3"
  CLOUDBOX_PATH: "/srv/git/cloudbox"

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: curl -s https://cloudbox.works/scripts/dep.sh | sudo -H sh

install:
  - sh: git submodule update --init --recursive
  - sh: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done
  - sh: curl -o daemon.json https://raw.githubusercontent.com/saltydk/AppveyorTest/main/daemon.json
  - sh: cp -f daemon.json /home/appveyor/projects/cloudbox-3c1ng/roles/docker/templates/daemon.json.j2
  - sh: sudo ansible-playbook cloudbox.yml --syntax-check
  - sh: |
      sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" \
          --skip-tags "settings" \
          --extra-vars '{"continuous_integration":true}'
  - sh: cd ~/cloudbox
  - sh: git fetch
  - sh: git reset --hard @{u}
  - sh: git checkout develop
  - sh: git reset --hard @{u}
  - sh: sudo pip install 'ansible>=2.9,<2.10'
  - sh: sudo ansible-playbook cloudbox.yml --tags user
  - sh: cd ~
  - sh: cb install user
  - sh: |
      sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" \
          --skip-tags "settings" \
          --extra-vars '{"continuous_integration":true}'
