---
build_cloud: COMMUNITY

image: 
  - Saltbox1804

matrix:
  fast_finish: false

build: off
test: off

environment:
  matrix:

  - job_name: airdcpp
  - job_group: test
  - job_name: airsonic
  - job_group: test
  - job_name: alltube
  - job_group: test

    only_commits:
      message: /airdcpp/

for:

  -
    matrix:
      only:
        - job_group: test
      only_commits:
        message: /${APPVEYOR_JOB_NAME}/
 
    install:
  - sh: uname -a


