---
image: 
  - Ubuntu1804
  - Ubuntu2004

build: off
test: off

install:
  - sh: lsb_release -a
  - sh: curl -s https://raw.githubusercontent.com/Cloudbox/cb/develop_python3/cb_install.sh | sudo -H bash -s -v; | cd /srv/git/cloudbox
  - sh: sudo ansible-playbook cloudbox.yml --syntax-check
  - sh: sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" \
          --skip-tags "settings" \
          --extra-vars '{"continuous_integration":true}'
