---
build_cloud: COMMUNITY

image: 
  - Saltbox1804

matrix:
  fast_finish: false

build: off
test: off

environment:
  matrix:

  - job_name: airdcpp
    only_commits:
      message: /airdcpp/
  - job_name: airsonic
    only_commits:
      message: /airsonic/
  - job_name: alltube
    only_commits:
      message: /alltube/

install:
  - sh: uname -a
