---
version: 1.0.0-{build}

image: Ubuntu1804-minimal

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: echo "$env:TESTVAR"
  - sh: echo "${TESTVAR}"
  - sh: echo "$TESTVAR"

install:
  - sh: echo "$TESTVAR"
