---
version: 1.0.0-{build}

skip_tags: true

skip_commits:
  files:
    # git
    - '.gitignore'
    - '.gitmodules'
    - '.github/**/*'

    # docs
    - '*.md'

    # vagrant
    - 'Vagrantfile'

    # ansible config
    - 'defaults/**/*'
    - 'filter_plugins/**/*'
    - 'inventories/**/*'
    - 'library/**/*'

    # ansible roles
    - 'roles/*/files/**/*'
    - 'roles/settings/**/*'
    - 'roles/backup/**/*'
    - 'roles/restore/**/*'

    # ansible roles extras	
    - 'roles/cloudflare/**/*'	
    - 'roles/ddclient/**/*'	
    - 'roles/feeder/**/*'	
    - 'roles/mariadb/**/*'	
    - 'roles/nginx/**/*'	
    - 'roles/notify/**/*'	
    - 'roles/nvidia/**/*'	
    - 'roles/nzbthrottle/**/*'	
    - 'roles/plex_auth_token/**/*'	
    - 'roles/plex_dupefinder/**/*'	
    - 'roles/plex_patrol/**/*'	
    - 'roles/python-plexlibrary/**/*'	
    - 'roles/resilio-sync/**/*'	
    - 'roles/sickbeard_mp4_automator/**/*'	
    - 'roles/subliminal/**/*'	
    - 'roles/traktarr/**/*'	

  message: /\[minor\]/

image: Ubuntu1804-minimal

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: echo "$env:TESTVAR"

install:
  - sh: echo "$env:TESTVAR"
