---
version: 1.0.0-{build}

image: Ubuntu1804-minimal

environment:

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: echo "Init called"

for:

  -
    matrix:
      only:
        - job_name: Job1

    build_script:
    - sh: echo "Job1 called"

  -
    matrix:
      only:
        - job_name: Job2

    build_script:
    - sh: echo "Job2 called"
