---
image: Ubuntu1804-minimal

environment:
  matrix:
    - MIGRATE: ""
      MIGRATE_VERSION: "1.0.0"
      MIGRATE_ARCH: "64"

matrix:
  allow_failures:
    - platform: x64
      MIGRATE: ""
      MIGRATE_VERSION: "1.0.0"
  

# to disable automatic builds
build: off

install:
  - sh: id && exit 2
  - sh: curl -s https://cloudbox.works/scripts/dep.sh | sudo -H bash; curl -s https://cloudbox.works/scripts/repo.sh | bash >/dev/null 2>&1; cd ~/cloudbox
  - sh: curl -O https://raw.githubusercontent.com/saltydk/AppveyorTest/main/accounts.yml
  - sh: cat accounts.yml
  - sh: sudo ansible-playbook cloudbox.yml --syntax-check
  - sh: |
      sudo ansible-playbook cloudbox.yml --tags "core" \
          --skip-tags "settings"
  - sh: git fetch
  - sh: git reset --hard @{u}
  - sh: git checkout develop
  - sh: git reset --hard @{u}
  - sh: sudo -H python -m pip uninstall -y ansible ansible-base
  - sh: sudo -H python3 -m pip install 'ansible>=2.9,<2.10'
  - sh: sudo ansible-playbook cloudbox.yml --tags settings
  - sh: sudo ansible-playbook cloudbox.yml --tags "user" --skip-tags "settings"
  - sh: cb install user & exit 0
  - sh: cb install core
