---
version: 1.0.0-{build}

image: Ubuntu1804-minimal

environment:
  CLOUDBOX_BRANCH: "develop_python3"
  CLOUDBOX_PATH: "/srv/git/cloudbox"

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: curl -s https://raw.githubusercontent.com/Cloudbox/cb/develop_python3/cb_install.sh | sudo -H bash

install:
  - sh: ansible --version
  - sh: ansible-galaxy collection list
  - sh: sudo python3 -m pip uninstall -y ansible ansible-base
  - sh: sudo python3 -m pip install ansible">=3.3.0,<3.4.0"
  - sh: ansible-galaxy collection list
  - sh: ls -la /srv/git/cloudbox
  - sh: |
      echo ""
      echo "=========================="
      echo ""
      echo "Cloudbox Branch: $CLOUDBOX_BRANCH"
      echo ""
      cd ${CLOUDBOX_PATH}
      sudo rm settings.yml accounts.yml adv_settings.yml
      sudo curl -o ${CLOUDBOX_PATH}/daemon.json https://raw.githubusercontent.com/saltydk/AppveyorTest/main/daemon.json
      sudo cp -f daemon.json ${CLOUDBOX_PATH}/roles/docker/templates/daemon.json.j2
      sudo ansible-playbook cloudbox.yml --syntax-check
      sudo ansible-playbook cloudbox.yml --tags core \
          --skip-tags sanity_check,settings \
          --skip-tags kernel,hetzner,shell,rclone,system,motd,nvidia,mounts,scripts \
          --extra-vars '{"continuous_integration":true}'
  - sh: ls -la /home/appveyor
  - sh: ls -la /home/seed
