---
image: Ubuntu1804-minimal

environment:
  APPVEYOR_BAKE_IMAGE: cloudbox-master-1804

matrix:
  fast_finish: true

# to disable automatic builds
build: off

install:
  - sh: curl -s https://cloudbox.works/scripts/dep.sh | sudo -H bash; curl -s https://cloudbox.works/scripts/repo.sh | bash >/dev/null 2>&1; cd ~/cloudbox
  - sh: git submodule update --init --recursive
  - sh: for i in defaults/*; do cp -n $i "$(basename "${i%.*}")"; done
  - sh: sudo ansible-playbook cloudbox.yml --syntax-check
  - sh: |
      sudo ansible-playbook cloudbox.yml --tags "cloudbox,emby,netdata,sabnzbd" \
          --skip-tags "settings" \
          --extra-vars '{"continuous_integration":true}'
