---
version: 1.0.0-{build}

image: Ubuntu1804-minimal

matrix:
  fast_finish: true

# to disable automatic builds
build: off

init:
  - sh: curl -s https://raw.githubusercontent.com/Cloudbox/cb/develop_python3/cb_install.sh | sudo -H bash

install:
  - sh: ansible --version
  - sh: ls -la /srv/git/cloudbox
  - sh: ls -la /home/appveyor
  - sh: ls -la /home/seed
