name: build
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Read package.json
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: community.yml
      - name: Echo community.yml
        run: echo "${{ steps.package.outputs.content }}"
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"roles\":[\"test\",\"test2\",\"test3\"]}"
  job2:
    name: '${{ matrix.roles }}'
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo '${{ matrix.roles }}'
