name: build
on: [push, workflow_dispatch]
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Parse community.yml
        run: |
          export OUTPUT=`awk -F'[][]' -e '/ role:/ && FNR > 13' community.yml | awk -F'[][]' '{print $2}' | tr '\n' ',' | sed 's/,*$//' | sed "s/.\(airsonic\|alltube\).,//g"`
          echo "::set-output name=content::$OUTPUT"
        id: validroles
      - id: set-matrix
        run: echo "${{ steps.validroles.outputs.content }}"
  job2:
    name: '${{ matrix.roles }}'
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
    - run: echo '${{ matrix.roles }}'
