name: install

on: [push, pull_request, workflow_dispatch]
strategy:
  matrix:
    roles: 
      - airdcpp 
      - airsonic 
      - alltube 
      - alternatrr 
      - alternatrrx 
      - asshama 
      - autoscan 
      - deluge 
      - grafana 
      - influxdb 
      - lidarrx 
      - ombi 
      - ombix 
      - prowlarr 
      - qbittorrent 
      - radarrx 
      - sonarrx 
      - speedtest 
      - transfer 
      - transmission
  fail-fast: false
jobs:
  # This workflow contains a single job called "build"
  ${{ matrix.roles }}:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04


    steps:
      - name: Install Dependencies
        run: curl https://raw.githubusercontent.com/saltyorg/sb/master/sb_install.sh --output sb_install.sh && sudo bash sb_install.sh -v

      - name: Chown /srv/git
        run: sudo chown -R runner:runner /srv/git

      - name: Remove accounts.yml
        run: cd /srv/git/saltbox && rm -rf accounts.yml

      - name: Download Github Actions accounts.yml
        run: cd /srv/git/saltbox && curl -o accounts.yml https://raw.githubusercontent.com/saltydk/AppveyorTest/main/github.yml

      - name: Create, chown and chmod /tmp/ansible
        run: sudo mkdir /tmp/ansible && sudo chown -R runner:runner /tmp/ansible && chmod 0777 /tmp/ansible

      - name: Syntax Check
        run: cd /srv/git/saltbox && sudo ansible-playbook saltbox.yml --syntax-check

      - name: Install Saltbox
        run: cd /srv/git/saltbox && sudo ansible-playbook saltbox.yml --tags "core,community" --skip-tags "sanity_check,settings,kernel,hetzner,shell,rclone,system,motd,nvidia,mounts,scripts" --extra-vars '{"continuous_integration":true}'

      - name: Copy default configuration
        run: cd /opt/community && cp -n defaults/ansible.cfg.default ansible.cfg && cp -n defaults/settings.yml.default settings.yml

      - name: Install ${{ matrix.roles }}
        run: cd /opt/community && sudo ansible-playbook community.yml --tags "${{ matrix.roles }}" --skip-tags "sanity_check,settings" --extra-vars '{"continuous_integration":true}'
